### ISSUE TITLE
Error reading XLS: "Unable to allocate memory", file seems fine

### ISSUE THREAD

**Issue by abissellsiders** [libxls/libxls#75] opened 2020-05-22 21:17 UTC
Hello,

I attempted to read [this XLS](https://images.transparencycdn.org/images/2012_CPI_DataPackage.zip) (zipped) from T[ransparency International's 2012 Corruption Perception Index](https://www.transparency.org/en/cpi/2012) (all other years are XLSX or CSV) with the following R code:
```R
require("readxl")
# download file
url = "https://images.transparencycdn.org/images/2012_CPI_DataPackage.zip"
path = tempfile()
dir = tempdir()
download.file(url, path, mode="wb")
# read file
path2 = unzip(path, "2012_CPI_DataPackage/CPI2012_Results.xls", exdir=dir)
df_12 = read_excel(path2, sheet = 1, skip =1)
```

This error results:
```
Error: 
  filepath: C:\Users\desk\AppData\Local\Temp\Rtmp6leIcT\2012_CPI_DataPackage\CPI2012_Results.xls
  libxls error: Unable to allocate memory
```

The file seems valid: I can open the file on LibreOffice Calc. If re-saved as an XLSX, `read_excel("C:/Users/desk/Downloads/CPI2012_Results.xlsx")` runs without errors and returns a tibble:
![image](https://user-images.githubusercontent.com/32911019/82710234-67bd5700-9c50-11ea-8773-8ac4efb3a729.png)

Unzipping is not the issue: The issue also results after manually unzipping. `read_excel("C:/Users/desk/Downloads/CPI2012_Results.xls")` returns the same error:
```
Error: 
  filepath: C:\Users\desk\Downloads\CPI2012_Results.xls
  libxls error: Unable to allocate memory
```

Memory is not the issue: The issue also results on a fresh R session.

The file does have these comment thingies, but I don't know if it matters:

![image](https://user-images.githubusercontent.com/32911019/82709937-b74f5300-9c4f-11ea-90f9-5f4e69367d9e.png)

I think this issue has been discussed three times before: #14, #30, #65

Thanks for your time!

**Comment by evanmiller** [comment] 2020-06-06 12:55
Thanks for the report. It looks like this file is choking on the Shared String Table. Here are the last messages when I run `xls2csv` on the file:

```
----------------------------------------------
libxls : BOF
   ID: 00EBh MSODRAWINGGROUP (Microsoft Office Drawing Group)
   Size: 146
    Not Processed in parseWoorkBook():  BOF=0x00EB size=146
----------------------------------------------
libxls : BOF
   ID: 00FCh SST (Shared String Table)
   Size: 2327
libxls : xls_addSST
libxls : xls_close
Error reading XLS file: Unable to allocate memory
```

Digging in further, the string count appears to be set to `-624266443`, which is obviously incorrect. (Note to self: The byte offset for that number is 3411.)

This does look very close to issue #30, as both are seeing an invalid size for a shared string table. A further similarity between the two files is the fact that `MSODRAWINGGROUP` precedes the supposed string table. If I interpret the invalid byte sequence as two 16-bit integers, rather than a single 32-bit integer, the numbers are 29493 and 56010. Call me superstitious, but the first number is quite close to 29561, the first number seen in issue #30.

I suspect that this is not a Shared String Table at all, but some record related to the drawing group. I feel confident that this is a duplicate of issue #30 so with these two test cases in hand, I might be able to make some progress on it.

**Comment by evanmiller** [comment] 2020-06-06 13:26
Further note: Looking through the file in a hex editor, I don't see any of the strings that appear in the opened file. So another possibility is that this is some kind of compressed string table.

**Comment by evanmiller** [comment] 2020-06-06 13:42
Closing as duplicate of #30, please continue discussion there.

**Closed by evanmiller** 2020-06-06 13:42 UTC
