### ISSUE TITLE
"Unable to allocate memory" with a fairly innocuous-looking xls

### ISSUE THREAD

**Issue by jennybc** [libxls/libxls#65] opened 2019-07-05 17:44 UTC
Original report from https://github.com/tidyverse/readxl/issues/578

I have reproduced the report. Namely that this file

https://www.gov.scot/binaries/content/documents/govscot/publications/statistics/2014/11/recorded-crime-scotland-2013-14/documents/recorded-crime-scotland-2013-14-excel-tables/recorded-crime-scotland-2013-14-excel-tables/govscot%3Adocument/00467392.xls

can't be read with readxl, but really libxls. I see:

``` r
> read_excel("~/Downloads/00467392.xls")
Error: 
  filepath: /Users/jenny/Downloads/00467392.xls
  libxls error: Unable to allocate memory
``` 
 
It's not really that large. It has lots of worksheets, but it's not obvious to me why it's a dealkiller.

*Contrary to what OP reports, if I save this as xlsx in Excel, then I can read it with readxl, which travels an entirely different code path.*

**Comment by nacnudus** [comment] 2019-07-07 14:43
It seems to be something to do with sheets "Table A1" to "Table A5".  Here's "Table 1" when opened with Excel 2010:

![image](https://user-images.githubusercontent.com/3522552/60769850-94b25b00-a0cc-11e9-8a4a-ffdeda42e015.png)

Whereas this is also "Table 1" opened with [Office Editing for Docs, Sheets & Slides](https://chrome.google.com/webstore/detail/office-editing-for-docs-s/gbkeegbaiigmenfmjfclcdgdpimamgkj) Chrome extension by Google.

![image](https://user-images.githubusercontent.com/3522552/60769866-d5aa6f80-a0cc-11e9-9941-6fb7b23a234f.png)

"Table A2" to "Table A5" are similar.  But then the Google Extension version of "Table A6" is the same as the Excel 2010 version of "Table A1".

**Google: Table A6**
![image](https://user-images.githubusercontent.com/3522552/60769949-a9dbb980-a0cd-11e9-833c-d9854dde1aa3.png)

**Excel: Table A1**
![image](https://user-images.githubusercontent.com/3522552/60769959-d394e080-a0cd-11e9-9a17-9d55638abd18.png)

That misalignment continues up to Google's "Table A9" being Excel's "Table A4".

The final three sheets in Google's version seem completely different from anything in Excel's version: "Population", "Annex 1" and "Annex 2".  Excel's versions of those sheets aren't in the Google extension version.

**Comment by evanmiller** [comment] 2020-06-06 13:32
Output from `xls2csv -v`:

```
----------------------------------------------
libxls : BOF
   ID: 00EBh MSODRAWINGGROUP (Microsoft Office Drawing Group)
   Size: 8224
    Not Processed in parseWoorkBook():  BOF=0x00EB size=8224
----------------------------------------------
libxls : BOF
   ID: 003Ch CONTINUE (Continues Long Records)
   Size: 8224
----------------------------------------------
...many more...
----------------------------------------------
libxls : BOF
   ID: 003Ch CONTINUE (Continues Long Records)
   Size: 282
----------------------------------------------
libxls : BOF
   ID: 00FCh SST (Shared String Table)
   Size: 8213
libxls : xls_addSST
libxls : xls_close
```

Like #75 and #30 this follows the pattern of `MSODRAWINGGROUP` followed by an invalid `SST` record.

**Comment by evanmiller** [comment] 2020-06-06 13:41
Closing as duplicate of #30, please continue discussion there.

**Closed by evanmiller** 2020-06-06 13:41 UTC
